services:
  iconproject:
    image: iconproject
    build:
      context: .
      dockerfile: IconProject/Dockerfile

  iconproject.common:
    image: iconproject.common
    build:
      context: .
      dockerfile: IconProject.Common/Dockerfile

